### ISSUE TITLE
Mapear API do Mapas para buscar Unidade de Saúde e mostrar na tela de ordem de entrega de equipamento

### ISSUE THREAD

**Issue by camilaccolares** [EscolaDeSaudePublica/gestao-ventiladores-front#18]
Uirá forneceu esse link com a documentação da API, mas estou achando os endereços dos endpoints estranhos.

https://github.com/EscolaDeSaudePublica/MapaDaSaude/blob/develop/documentation/docs/mc_config_api.md

**Comment by chicaothiago** [comment]
Criar um arquivo mapasApiService dentro da pasta services e criar funções para cada endpoint utilizando axios.

Dentro da pasta modulesService há exemplos de como fazer

**Comment by Junior-Shyko** [comment]
Resolvido no commit da issue 18
https://github.com/EscolaDeSaudePublica/gestao-ventiladores-front/commits/feature/issue18
