### ISSUE TITLE
Desenvolver Header do layout

### ISSUE THREAD

**Issue by chicaothiago** [EscolaDeSaudePublica/gestao-ventiladores-front#6]
Imagem de referência:
![header2](https://user-images.githubusercontent.com/6399202/79574020-e5140b80-8095-11ea-9bcf-4c1108449212.JPG)

Figma: https://www.figma.com/file/OCBwphdiOoIXCd47xN3HUj/Software-de-Ventiladores?node-id=1%3A159

Orientações:

Componente para os menus:
https://material-ui.com/components/bottom-navigation/

Menu do usuário logado:
https://material-ui.com/components/menus/

**Comment by Junior-Shyko** [comment]
Desenvolvido com Menu e MenuItem do material-ui - Enviado com feature issue06
